### ISSUE TITLE
An entire file should be a valid slice range

### ISSUE THREAD

**Issue by jwparsons** [jungaretti/digist#58]
### Repro Steps

- Visit https://gist.github.com/jwparsons/b8bcfe1023296fabe6eb66dbfbaa684e
- Notice that `test.cpp` has 34 lines
- Visit https://digist.azurewebsites.net/gist/b8bcfe1023296fabe6eb66dbfbaa684e?file=test.cpp&slice=14:34
- Notice that an invalid range error appears
- Visit https://digist.azurewebsites.net/gist/b8bcfe1023296fabe6eb66dbfbaa684e?file=test.cpp&slice=14:33
- Notice that the request returns successfully

I'd expect `https://digist.azurewebsites.net/gist/b8bcfe1023296fabe6eb66dbfbaa684e?file=test.cpp&slice=14:34` to be a valid request since `test.cpp` has 34 lines.

**Comment by jungaretti** [comment]
I think the bug is in `checkSliceInFile`

**Comment by jwparsons** [comment]
In a perfect world, unit tests would have caught this. :rainbow:

**Comment by KartikM123** [comment]
That is my function my bad. Did you find the bug?

**Comment by jungaretti** [comment]
Spirit of the Hackathon @jwparsons

**Comment by KartikM123** [comment]
Wait I know the bug. It is a > start && > stop but it should be >= start && >= stop because there 33 '\n' means 34 lines
